### ISSUE TITLE
1. Extend to SC and BCC

### ISSUE THREAD

**Issue by emeryjdk** [ageller/EmeryInteractive#12]
Extend FCC model to simple cubic and HCP.

**Comment by ageller** [comment]
Jon did this, and will issue me a pull request.  Then I need to make an index that allows users to choose which (and add the analytics).

**Comment by ageller** [comment]
Jon will also give me positions for interstitials.  I will add them.  Also I need to enable coordinations

**Comment by emeryjdk** [comment]
Attached are the SC and BCC void positions. @ageller
[BCC-SC Interstitial.txt](https://github.com/ageller/EmeryInteractive/files/3810632/BCC-SC.Interstitial.txt)

**Comment by ageller** [comment]
interstitials are added.  The final step will be to enable the coordinations; @emeryjdk do you want to specify the coordinates for these views (only the main atoms probably), or should I/we work out an algorithm for this and apply it here?

**Comment by emeryjdk** [comment]
Addressed in #16. For now, let's hard-code. 

In the future it would be massively helpful for students to click on an "activate nearest-neighbor coordination" button. This should be too hard.

I think for us, an algorithm that searches a list of atoms for one that has the smallest distance and populates lists of "nearest-neighbors" and "next-nearest neighbors". The only weakness here is that if an atom isn't rendered (e.g., the BCC octahedral and tetrahedral sites), how can we have the system search nearby unit cells without this getting too messy?

@ageller

**Comment by ageller** [comment]
Marking as closed for now, but let's try to remember your idea for "activate nearest-neighbor coordination" for a future enhancement
