### ISSUE TITLE
Atomic Coordination in SC not rendering.

### ISSUE THREAD

**Issue by emeryjdk** [ageller/EmeryInteractive#34]
Hey @ageller, when I try to show coordination for the atoms in the SC model, nothing shows. Any idea what's going on there?

**Comment by ageller** [comment]
It looks like there is no atomic coordination coded in for the SC or BCC models.  If you send me the locations for these, I can code it in.  (Sorry if you sent those to me in the past, and I somehow forgot to include them.)

**Comment by emeryjdk** [comment]
Got it! I'll send them later tomorrow.

**Comment by emeryjdk** [comment]
Hi @ageller:

For BCC, the atom at (0.5 0.5 0.5) should be coordinated with the eight atoms on the corners: (000). (100), (010), (001), (110), (101), (011), (111).

For SC, we can look at the atom at the origin (0 0 0) coordinated with (0.5 0 0), (0 0.5 0), and (0 0 0.5), as well as their negatives: (-0.5 0 0), (0 -0.5 0), (0 0 -0.5). Six in total.

In the future it might be a good idea to show atomic coordination for more than one atom - at least for FCC and BCC.

Thanks!

**Comment by ageller** [comment]
@emeryjdk I added in the coordination for the BCC and SC.  Please take a look, and let me know if it's correct.  In particular I am wondering if the SC is correct, since the normal view has atoms at the corners, but the coordination has atoms in the middle; should those atoms be at distances of 1 instead of 0.5?

**Comment by emeryjdk** [comment]
@ageller Sorry yes, please replace all those distances with 1s. Not 0.5s. Thanks!

**Comment by ageller** [comment]
Done!
